# Generated by Django 5.2.3 on 2025-07-17 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.CharField(max_length=100)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("borehole", "Borehole"),
                            ("domestic water treatment", "Domestic Water Treatment"),
                            (
                                "industrial water treatment",
                                "Industrial Water Treatment",
                            ),
                            ("consulting", "Consulting"),
                            ("others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "project_display",
                    models.ImageField(
                        blank=True, null=True, upload_to="project-display/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="services",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ProjectImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_images", models.ImageField(upload_to="project-images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="freshspring_app.projects",
                    ),
                ),
            ],
        ),
    ]
