# Generated by Django 5.2.3 on 2025-07-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freshspring_app",
            "0002_projects_services_created_at_services_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=14, null=True)),
                ("request", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
