# Generated by Django 5.2.3 on 2025-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0003_contactmessages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("profession", models.CharField(blank=True, max_length=50, null=True)),
                ("testimony", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="/static/freshspring_app/images/user/user-image-6.png",
                        upload_to="testimonial-images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="contactmessages",
            name="request",
            field=models.CharField(
                choices=[
                    ("borehole", "Borehole"),
                    ("domestic water treatment", "Domestic Water Treatment"),
                    ("industrial water treatment", "Industrial Water Treatment"),
                    ("consulting", "Consulting"),
                    ("general", "General Enquiry"),
                ],
                max_length=100,
            ),
        ),
    ]
