# Generated by Django 5.2.3 on 2025-07-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0005_blog_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/static/freshspring_app/images/user/user-image-6.png",
                null=True,
                upload_to="testimonial-images/",
            ),
        ),
    ]
