# Generated by Django 5.2.3 on 2025-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0006_alter_testimonial_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                default="defaults/user-image-6.jpg",
                null=True,
                upload_to="testimonial-images/",
            ),
        ),
    ]
