# Generated by Django 5.2.3 on 2025-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0007_alter_testimonial_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
