# Generated by Django 5.2.3 on 2025-08-08 00:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0008_comment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field('Text', config_name='default'),
        ),
    ]
