# Generated by Django 5.2.3 on 2025-08-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0009_alter_blog_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBannerSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for the section",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("satisfied_customers", models.CharField(max_length=50)),
                ("positive_rating", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HomeBannerContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("icon_text", models.CharField(blank=True, max_length=100, null=True)),
                ("header", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("banner_image", models.ImageField(upload_to="homebanner_images/")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="freshspring_app.homebannersection",
                    ),
                ),
            ],
        ),
    ]
