# Generated by Django 5.2.3 on 2025-08-13 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0010_homebannersection_homebannercontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for the section",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("icon_text", models.CharField(blank=True, max_length=100, null=True)),
                ("header", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HomeBannerContent",
        ),
        migrations.DeleteModel(
            name="HomeBannerSection",
        ),
    ]
