# Generated by Django 5.2.3 on 2025-08-13 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freshspring_app",
            "0011_pagesection_staticcontent_delete_homebannercontent_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_title", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=25)),
                ("whatsapp", models.CharField(blank=True, max_length=25, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "larger_image",
                    models.ImageField(blank=True, null=True, upload_to="about-image/"),
                ),
                (
                    "smaller_image",
                    models.ImageField(blank=True, null=True, upload_to="about-image/"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagesectionabout",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_item", models.CharField()),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="freshspring_app.about",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomeBannerContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("icon_text", models.CharField(blank=True, max_length=100, null=True)),
                ("header", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagesectionbanner",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="treatment-icon/"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagesectiontreatment",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tilte", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagesectionvalue",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
    ]
