# Generated by Django 5.2.3 on 2025-08-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freshspring_app",
            "0012_contactinformation_about_aboutlist_homebannercontent_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinformation",
            old_name="update_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="value",
            name="position",
            field=models.CharField(default="freshspring", max_length=50),
            preserve_default=False,
        ),
    ]
