# Generated by Django 5.2.3 on 2025-08-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freshspring_app",
            "0013_rename_update_title_contactinformation_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homebannercontent",
            name="client",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="homebannercontent",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homebannercontent",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="home-banner-images/"
            ),
        ),
        migrations.AddField(
            model_name="homebannercontent",
            name="rating",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pagesection",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="aboutlist",
            name="about",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to="freshspring_app.about",
            ),
        ),
    ]
