# Generated by Django 5.2.3 on 2025-08-14 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "freshspring_app",
            "0014_homebannercontent_client_homebannercontent_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentcontent",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="treatment-icon/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
            ),
        ),
    ]
