# Generated by Django 5.2.3 on 2025-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0015_alter_treatmentcontent_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentcontent",
            name="serial",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
