# Generated by Django 5.2.3 on 2025-08-15 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0016_treatmentcontent_serial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagesectionfeatures",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FunFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("paragraph", models.IntegerField()),
                ("years", models.CharField(max_length=100)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagesectionfunfact",
                        to="freshspring_app.pagesection",
                    ),
                ),
            ],
        ),
    ]
