# Generated by Django 5.2.3 on 2025-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0017_feature_funfact"),
    ]

    operations = [
        migrations.AddField(
            model_name="funfact",
            name="position",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="funfact",
            name="paragraph",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="funfact",
            name="years",
            field=models.IntegerField(),
        ),
    ]
