# Generated by Django 5.2.3 on 2025-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0018_funfact_position_alter_funfact_paragraph_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="value",
            old_name="tilte",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="funfact",
            name="position",
            field=models.IntegerField(unique=True),
        ),
    ]
