# Generated by Django 5.2.3 on 2025-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freshspring_app", "0019_rename_tilte_value_title_alter_funfact_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinformation",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
